UART
riscv-rust/k210-pac pull request #15
Opened 2019-05-06 13:06 UTC by laanwj

Structure from `lib/drivers/include/uart.h` in SDK.
Register descriptions from https://linux-sunxi.org/images/d/d2/Dw_apb_uart_db.pdf .

Did not fill in the field names and descriptions, the above PDF mentions them too, though, so this would be straightforward work if we can be confident enough that the part matches apart from the register offsets and names.

2019-05-13 11:18 UTC, Disasm requested changes

2019-05-13 11:18 UTC, Disasm commented on k210.svd
> +                    <description>Shadow Receive Buffer Register / Shadow Transmit Holding Register (depending on R/W)</description>
This one must be declared with `<dim>`.

2019-05-14 09:50 UTC, laanwj commented
Thanks, good catch. Updated to add `<dim>` and `<dimIncrement>`.

2019-05-14 09:51 UTC, Disasm approved these changes

2019-05-14 10:07 UTC, merged