rtc
riscv-rust/k210-pac pull request #5
Opened 2019-04-17 14:33 UTC by burrbull

2019-04-19 19:30 UTC, Disasm requested changes

2019-04-19 19:30 UTC, Disasm commented on k210.svd
> +                            <bitRange>[4:0]</bitRange>
Seems like there is a mistake here.

2019-04-20 03:41 UTC, burrbull commented on k210.svd
> +                            <bitRange>[4:0]</bitRange>
Done.

2019-04-20 06:00 UTC, Disasm approved these changes

2019-04-20 06:00 UTC, merged