dvp
riscv-rust/k210-pac pull request #6
Opened 2019-04-17 18:30 UTC by burrbull

2019-04-19 19:40 UTC, Disasm requested changes

2019-04-19 19:40 UTC, Disasm commented on k210.svd
> +                                <description>MODE</description>
Could you commit these `TIMER` fixes in separate PR?

2019-04-19 19:40 UTC, Disasm commented on k210.svd
> +                            <name>FORMAT</name>
Maybe lowercase is more suitable here

2019-04-19 19:44 UTC, Disasm commented
Sorry for me being slow and thanks for your effort! I'll be happy to merge this as soon as you fix these minor issues.

2019-04-20 06:25 UTC, burrbull commented
Done.

2019-04-25 04:47 UTC, merged