I2s
riscv-rust/k210-pac pull request #8
Opened 2019-04-20 10:13 UTC by burrbull

2019-04-20 10:14 UTC, burrbull commented on src/i2s0.rs
> +    #[doc = "0x38 - _RESERVED0"]
Small hack.

2019-04-30 16:10 UTC, Disasm requested changes
Thanks for contributing! There are some debatable moments, however. I can merge the PR as soon as we agree on them.

2019-04-30 16:10 UTC, Disasm commented on k210.svd
> +                            <enumeratedValues>
I doubt that it is useful to have enumerated values for one-bit "enables".

2019-04-30 16:10 UTC, Disasm commented on k210.svd
> +                            </enumeratedValues>
Here we have reusing the same enumerated values, but with different meaning: "receiver enabled" vs "i2s enabled". Maybe it is suitable for other use-cases, but not for Rust.

2019-04-30 16:10 UTC, Disasm commented on k210.svd
> +                                    <description>Clock gating is disable</description>
```suggestion
                                    <description>Clock gating is disabled</description>
```

2019-04-30 16:10 UTC, Disasm commented on k210.svd
> +                                <enumeratedValues derivedFrom="rer.rxchenx.ENABLE">
Same issue with enum reuse.

2019-04-30 16:46 UTC, Disasm approved these changes

2019-04-30 16:47 UTC, merged